### ISSUE TITLE
Missing information of strand function

### ISSUE THREAD

**Issue by denise0593** [telatin/bamtocov#5]
Hi! 
I'm trying you strand coverage calculator, using the command: 
bamtocov -s alignment.rg.clipped.recalibrated.bam > stranded_cov.txt
But I couldn't found any indication about the strand output, is the first column the forward and the second column the reverse?
Thanks

**Comment by telatin** [comment]
Hello @denise0593, thanks for reporting!

Yes, with `--stranded` you will get two columns, one for the forward reads and one for the reverse.
There is a hint here https://telatin.github.io/bamtocov/tools/bamtocov.html#bam-to-bedgraph, and 
we are in the process of expanding the documentation as well. I'll close the issue when the new
docs will be live!

Thanks for the feedback!

**Comment by telatin** [comment]
Hi there, I added a paragraph for now,
but in an upcoming version, an entire page will be dedicated to stranded and physical coverage.
https://telatin.github.io/bamtocov/tools/bamtocov.html#stranded-output

Thanks for reporting!
